### ISSUE TITLE
Добавить проверку инициализации

### ISSUE THREAD

**Issue by serykhelena** [chirkofun/TESTS#12]
В функциях инициализации лучше добавить условия на проверку, был ли уже инициализирован данный модуль. 
Например ->
`static bool         isInitialized       = false;`
`void lldEncoderInit( void )`
`{`
`    if ( isInitialized )`
`            return;`
`    extStart( &EXTD1, &extcfg );`
`    /* Set initialization flag */`
`    isInitialized = true;`
`}`

**Comment by chirkofun** [comment]
https://github.com/chirkofun/TESTS/commit/359b7c98522b339c082574a35c955b0c9e2e3f88

Добавил
