### ISSUE TITLE
[enc.c] Зачем условие в callback EXT

### ISSUE THREAD

**Issue by serykhelena** [chirkofun/TESTS#6]
Будет ли когда-нибудь выполняться условие `if` или сразу пойдёт на `else` ? 
Когда вызывается callbalck?
Почему используешь детектирование по срезу?

**Comment by chirkofun** [comment]
По фронту или по срезу без разницы, просто так мне удобнее. Условие `if` будет выполнять если вращать по часовой, а `else` если против часовой. Там же канал А опаздыет на 90 гр. по сравнению с каналом Б, если мы вращаем по часовой. При срабатывании прерывания на срез идет проверка канала Б и если там единица, значит вращение по часовой, а если ноль, то против.

**Comment by serykhelena** [comment]
Я сначала думала, что ты проверяешь пин, по которому срабатывает прерывание, с макросами стало намного проще не перепутать (=
